on:
  pull_request: null
  workflow_call:
    inputs:
      extensions:
        description: List of extensions to PHP.
        default: sockets
        required: false
        type: string
  push:
    branches:
      - '*.*'

name: Rector

jobs:
  rector:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
        os: [ 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure environment
        run: |
          export COMPOSER_ROOT_VERSION=$(/usr/bin/jq --null-input --raw-output 'first(inputs["extra"]["branch-alias"])[]' composer.json)
          echo COMPOSER_ROOT_VERSION=$COMPOSER_ROOT_VERSION >> $GITHUB_ENV

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: ${{ matrix.coverage }}
          tools: pecl

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore Composer Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run Rector checks
        run: vendor/bin/rector process --dry-run
